from functools import partial

from langchain.schema.runnable import ConfigurableField
from langchain_core.runnables.base import RunnableSerializable
from langchain_core.runnables.utils import AnyConfigurableField, Input, Output
from langchain_openai import OpenAI

from heavyiq.langchain.llms import LLMType, get_llm_by_type


def make_llm_configurable(
    llm_type: LLMType, default_temperature: float = 0.0, **kwargs: AnyConfigurableField
) -> RunnableSerializable[Input, Output]:
    """
    Make an llm runnable configurable.

    Args:
        llm_type: LLM Type

    Returns:
        RunnableSerializable to be passed an alternative.
    """

    return get_llm_by_type(llm_type, temperature=default_temperature).configurable_fields(**kwargs)


llm_configurable_fields = {
    "temperature": ConfigurableField(
        id="llm_temperature",
        name="LLM Temperature",
        description="The temperature of the LLM",
    ),
    "n": ConfigurableField(
        id="llm_n",
        name="LLM Output Generations",
        description="Number of outputs generated by LLM",
    ),
    "max_tokens": ConfigurableField(
        id="llm_max_tokens",
        name="LLM Max tokens",
        description="Maxium output tokens to be generated by a LLM",
    ),
}

llm_runnable = (
    OpenAI(temperature=0, openai_api_key="nothing")  # type: ignore
    .configurable_alternatives(
        ConfigurableField(id="llm"),
        default_key="openai",
        nl_to_sql=partial(make_llm_configurable, LLMType.NL_TO_SQL, default_temperature=0.0, **llm_configurable_fields),  # type: ignore
        nl_to_sql_error=partial(make_llm_configurable, LLMType.NL_TO_SQL_ERROR, default_temperature=0.0, **llm_configurable_fields),  # type: ignore
        sql_to_answer=partial(make_llm_configurable, LLMType.SQL_TO_ANSWER, default_temperature=0.0, **llm_configurable_fields),  # type: ignore
        nl_to_tables=partial(make_llm_configurable, LLMType.NL_TO_TABLES, default_temperature=0.0, **llm_configurable_fields),  # type: ignore
        nl_to_multiple_sql=partial(
            make_llm_configurable, LLMType.NL_TO_MULTIPLE_SQL, default_temperature=0.0, **llm_configurable_fields
        ),
        tables_to_questions=partial(
            make_llm_configurable, LLMType.TABLES_TO_QUESTIONS, default_temperature=0.0, **llm_configurable_fields
        ),  # type: ignore
        default_llm=partial(make_llm_configurable, LLMType.DEFAULT, default_temperature=0.0, **llm_configurable_fields),  # type: ignore
    )
    .configurable_fields(
        temperature=ConfigurableField(
            id="llm_temperature",
            name="LLM Temperature",
            description="The temperature of the LLM",
        )
    )
)
