import os

from langchain.chat_models import ChatOpenAI
from langchain.docstore.document import Document
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain.schema import HumanMessage, SystemMessage
from langchain.vectorstores import Chroma


from modules.langchain.heavydb import HeavyDB

heavydb = HeavyDB.from_env()


# Embed and store the texts
# Supplying a persist_directory will store the embeddings on disk
persist_directory = "db"

index_creator = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory": persist_directory})

# check if folder persist_directory exists
if os.path.exists(persist_directory):
    print(f"Using persisted embeddings. Delete the '{persist_directory}' folder and rerun to recompute embeddings.")
    vectorstore = Chroma(embedding_function=index_creator.embedding, persist_directory=persist_directory)
else:
    print("Computing embeddings. This may take a while...")
    llm = ChatOpenAI(model_name="gpt-4", client=None)
    docs = []
    for table in heavydb.get_table_names():
        table_info = heavydb.get_table_info([table])
        messages = [
            SystemMessage(
                content="You are a helpful assistant that takes SQL table schemas and sample data and generates a summary of the table contents. This information will be converted into embeddings for easy retrieval from a vectorstore. Do not summarize the sample data or give examples."
            ),
            HumanMessage(content=table_info),
        ]
        resp = llm(messages)
        print(f"Enriched table {table} with following summary generated by GPT-4:\n{resp.content}")
        page_content = f"{resp.content}\n\n{table_info}"
        metadata = {"source": table}
        docs.append(Document(page_content=page_content, metadata=metadata))

    index_creator = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory": persist_directory})
    sub_docs = index_creator.text_splitter.split_documents(docs)
    vectorstore = index_creator.vectorstore_cls.from_documents(
        sub_docs, index_creator.embedding, **index_creator.vectorstore_kwargs
    )

heavydb_index = VectorStoreIndexWrapper(vectorstore=vectorstore)
