import os

from langchain.chat_models import ChatOpenAI
from langchain.docstore.document import Document
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain.schema import HumanMessage, SystemMessage
from langchain.vectorstores import Chroma
from langchain.vectorstores.base import VectorStore

from modules.langchain.heavydb import HeavyDB

# Embed and store the texts
# Supplying a persist_directory will store the embeddings on disk
persist_directory = "db"


def generate_embeddings(directory: str) -> VectorStore:
    index_creator = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory": directory})

    if os.path.exists(directory):
        print(f"Using persisted embeddings. Delete the '{directory}' folder and rerun to recompute embeddings.")
        vectorstore = Chroma(embedding_function=index_creator.embedding, persist_directory=directory)
    else:
        heavydb = HeavyDB.from_env()
        print("Computing embeddings. This may take a while...")
        llm = ChatOpenAI(model_name="gpt-4", client=None)
        docs = []

        for table in heavydb.get_usable_table_names():
            table_info = heavydb.get_table_info([table])
            messages = [
                SystemMessage(
                    content="With respect to the SQL table schema and sample rows provided, please create a comprehensive response encompassing the following aspects: \n\nTitle: Choose a concise and descriptive title reflecting the table's purpose.\nDescription: Write a brief yet informative summary of the table's purpose and primary functionality. Discuss any noteworthy constraints or unique features that set it apart.\nKeywords: Identify a set of essential keywords, including but not limited to column names or relationships that facilitate search, retrieval, and document indexing.\n\nUpon completion, evaluate the coherence, accuracy, and relevance of the generated response to ensure that it adheres to the requirements outlined above, maximizing its value and usefulness for search and retrieval tasks."
                ),
                HumanMessage(content=table_info),
            ]
            resp = llm(messages)
            print(f"Enriched table {table} with following summary generated by GPT-4:\n{resp.content}")
            page_content = f"{resp.content}\n\n{table_info}"
            metadata = {"source": table}
            docs.append(Document(page_content=page_content, metadata=metadata))

        sub_docs = index_creator.text_splitter.split_documents(docs)
        vectorstore = index_creator.vectorstore_cls.from_documents(
            sub_docs, index_creator.embedding, **index_creator.vectorstore_kwargs
        )

    return vectorstore


vectorstore = generate_embeddings(persist_directory)
heavydb_index = VectorStoreIndexWrapper(vectorstore=vectorstore)
