openapi: '3.0.0'
info:
  title: HeavyAnalyst API
  version: "0.1"
  description: A simple REST API for interacting with HeavyNL
paths:
  /query:
    post:
      summary: Provided a question and (optionally) table(s), returns SQL that can be used to answer the question
      operationId: heavynl.api.handlers.query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatabaseQuestionAndTablesRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SQLStatement'
        500:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /question:
    post:
      summary: Provided a question and (optionally) tables(s), returns SQL and a NL Answer to the question
      operationId: heavynl.api.handlers.question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatabaseQuestionAndTablesRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerAndSQLStatement'
        500:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DatabaseTables:
      type: object
      description: Array of table names to limit the scope of the search/response and database name
      properties:
        tables:
          type: array
          items:
            type: string
        database_name:
          type: string
          description: Name of the database
        session_id:
          type: string
          description: Valid HeavyDB Session ID
      required:
        - tables
        - session_id
      example:
        tables:
          - usa_states
        session_id: xxxxx
    DatabaseQuestionAndTablesRequest:
      allOf:
        - $ref: '#/components/schemas/DatabaseTables'
        - $ref: '#/components/schemas/Question'
    Question:
      type: object
      description: Natural language question (prompts accepted)
      properties:
        question:
          type: string
      required:
        - question
      example:
        question: How many states begin with the letter A? What are they?
    SQLStatement:
      type: object
      description: A SQL statement
      properties:
        sql:
          type: string
        sql_complexity:
          type: integer
          description: The complexity level of the SQL statement
      example:
        sql: SELECT COUNT(*) AS num_states, STATE_NAME FROM usa_states WHERE STATE_NAME LIKE 'A%' GROUP BY STATE_NAME;
        sql_complexity: 3
    Answer:
      type: object
      description: Natural language answer
      properties:
        answer:
          type: string
      required:
        - answer
      example:
        answer: 4 states start with the letter A; Alaska, Arizona, Arkansas, and Alabama.
    AnswerAndSQLStatement:
      allOf:
        - $ref: '#/components/schemas/SQLStatement'
        - $ref: '#/components/schemas/Answer'
    ErrorResponse:
      type: object
      description: An error message
      properties:
        error:
          type: string
