[iq]
heavydb_host = "localhost"
heavydb_port = 6274
heavydb_protocol = "binary"
heavydb_dbname = "heavyai"
heavydb_username = "admin"
heavydb_password = "HyperInteractive"
openai_api_key = "sk-xxxxxxxxetc"
huggingface_embed_model = "sentence-transformers/all-mpnet-base-v2"
metadata_index_dir = "db"
table_documents_dir = "table_documents"
openai_gpt_model = "gpt-3.5-turbo-16k"

# optional, don't copy to your config if you don't have these
langsmith_project = ""
langsmith_api_key = ""

# Logging, these are defaults no need to copy to your config if not overriding
access_log_level = "INFO"
heavyiq_log_level = "INFO" # DEBUG is recommended for development
log_to_stdout = false      # true is recommended for development

# Custom LLM (optional, don't copy to your config if you aren't using a custom LLM solution)
custom_llm_type = "API" # API or AZURE
# Custom LLM API
custom_llm_api_base = ""             # base url of API
custom_llm_api_context_window = 2048 # context window limit
# Custom LLM AZURE
custom_llm_azure_openai_api_version = "2023-05-15" # API specification version
custom_llm_azure_openai_api_base = ""              # base url of API
custom_llm_azure_deployment_name = ""              # name of deployment
