version: '3'

services:
  heavyiq-api:
    container_name: heavyiq-api
    build:
      context: .
      dockerfile: Dockerfile.dev  # Specify the custom Dockerfile name
    volumes:
      - ./table_documents:/app/table_documents
      - ./db:/app/db
      - ./storage:/app/storage
      - ./heavyiq:/app/heavyiq
      - ./hf_models:/app/hf_models
    network_mode: "bridge"
    ports:
      - "8000:8000"
    command: ["gunicorn", "-b", ":8000", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--preload", "heavyiq.api:create_app('./config.toml')"]

  heavyiq-test:
    container_name: heavyiq-test
    build:
      context: .
      dockerfile: Dockerfile.test  # Specify the custom Dockerfile name
    volumes:
      - ./table_documents:/app/table_documents
      - ./db:/app/db
      - ./storage:/app/storage
      - ./hf_models:/app/hf_models
      - ./config.test.toml:/app/config.toml
    network_mode: "bridge"
    command: ['pytest', '/app/tests', '--disable-warnings', '-rs', '--config-path=./config.toml']

  whisper-cpp:
    container_name: whisper-cpp
    build:
      context: ./custom_models/whisper
      dockerfile: Dockerfile
    volumes:
      - ./custom_models/whisper/models:/app/models
    entrypoint: /app/entrypoint.sh
    environment:
      - HOST=0.0.0.0
    ports:
      - "8001:8001"
