[Licenses]
authorized_licenses:
    Apache Software
    apache 2.0
    Apache License 2.0
    Apache License Version 2.0
    BSD
    BSD License
    Historical Permission Notice and Disclaimer (HPND)
    HPND
    isc license
    isc license (iscl)
    mit
    mit license
    Mozilla Public License 2.0 (MPL 2.0)
    MPL-2.0
    Python Software Foundation
    The Unlicense (Unlicense)
    unlicense
    zlib

# unauthorized_licenses:
#   GPL v3

[Authorized Packages]
# Apache 2.0 (https://github.com/nmslib/hnswlib/blob/master/LICENSE)
hnswlib: 0.7.0