from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class ServerSettings(BaseSettings):
    """
    Uvicorn settings
    """

    host: str = Field(default="localhost", description="Listen address")
    port: int = Field(default=8006, description="Listen port")
    app_name: str = Field(default="HeavyIQ RAG", description="RAG approach using llama-index")
    debug: bool = Field(default=False, description="Run on debug mode or not.")


class RAGSettings(BaseSettings):
    """
    Settings related to RAG.
    """

    persistant_storage_dir: str = Field(
        default="data/index-storage",
        description="Local directory for storage index related data.",
    )
    persistant_collection_dir: str = Field(
        default="data/chromadb", description="Local directory where chormadb resides."
    )
    hf_embedding_model: str = Field(default="BAAI/bge-base-en-v1.5", description="HuggingFace Embedding model name.")
    collection_name: str = Field(default="iqrag", description="Name of the chromadb collection.")


class HeavyDBSettings(BaseSettings):
    """
    Settings related to HeavyDB connection establishment.
    """

    heavydb_host: str = Field(default="localhost", description="HeavyDB Host")
    heavydb_port: int = Field(default=6278, description="HeavyDB Port")
    heavydb_protocol: str = Field(default="binary", description="HeavyDB protocol")


class LLMSettings(BaseSettings):
    """
    Settings for accessing custom LLM model served by vllm server.
    """

    llm_model: str = Field(
        default="heavyai/heavyiq-deepseek-coder-33b-combo-v58-3072-tokens-questions-no-meta-lr-1-2-gc-1-5",
        description="LLM Model",
    )
    llm_api_url: str = Field(default="http://209.20.156.243:5000/v1", description="VLLM server completion url")
    llm_max_tokens: int = Field(default=256, description="Max tokens generated by the LLM")
    llm_temperature: float = Field(default=0.1, description="Temperature")


class Settings(ServerSettings, RAGSettings, HeavyDBSettings, LLMSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")


settings = Settings()
