DEFAULT_NL_TO_SQL_PROMPT = (
    "<|sql prompt|>\n",
    """You are an expert data analyst adept at writing SQL queries to answer user questions.

You have access to the following relational tables, with schemas below.

Alongside each text column, in parentheses "()" you will see the top 3 values followed by "..." for columns with more than 5 distinct values, or the top 5 values otherwise. For timestamp and date columns you will see the min/max range of the column.

{table_info}

{relevant_info}
Write a SQL query to answer the following question:
{input}""",
    "\n<|sql answer|>\n",
)


DEFAULT_NL_TO_SQL_ERROR_PROMPT = (
    "<|sql error prompt|>\n",
    """You generated a SQL query that generated an exception when executed in the HeavyDB database.

You have access to the following relation tables, with schemas below.

Alongside each text column, in parentheses "()" you will see the top 3 values followed by "..." for columns with more than 5 distinct values, or the top 5 values otherwise. For timestamp and date columns you will see the min/max range of the column.

{table_info}

In attempting to answer the following user question:

{input},
you generated the following SQL query:
{sql_cmd}
, which failed to run in the HeavyDB database, generating the following error:
{error}

{relevant_info}
Please alter the query to run without error in HeavyDB:""",
    "\n<|sql error answer|>\n",
)

DEFAULT_SQL_TO_ANSWER_PROMPT = (
    "<|english prompt|>\n",
    """The user asked the following question:
{input}

By considering the following columns:
{columns}

To answer the question, the following SQL query was generated:
{sql_cmd}

The following results were returned:
{sql_result}

Now explain the results in English, referencing the question and the SQL query as needed.""",
    "\n<|english answer|>\n",
)

DEFAULT_NL_TO_TABLES_PROMPT = (
    "<|table prompt|>\n",
    """You are an expert data analyst adept at analyzing user questions to determine the SQL tables required to generate an answer.

You have access to the following relational tables, with schemas below.

Alongside each text column, in parentheses "()" you will see the top 3 values followed by "..." for columns with more than 5 distinct values, or the top 5 values otherwise. For timestamp and date columns you will see the min/max range of the column.

{table_info}

{relevant_info}
Emit each table name along with a 1 if the table is required to answer the following user question, or a 0 if the table is not required.

Question: {input}
""",
    "\n<|table answer|>\n",
)

DEFAULT_TABLES_TO_QUESTIONS_PROMPT = (
    "<|table question prompt|>\n",
    """You are an expert data analyst adept at asking compelling questions of your data.

You have access to the following relational tables, with schemas below.

Alongside each text column, in parentheses "()" you will see the top 3 values followed by "..." for columns with more than 5 distinct values, or the top 5 values otherwise. For timestamp and date columns you will see the min/max range of the column.

{table_info}

Write a compelling question to ask of the above data:""",
    """\n<|table question answer|>\n""",
)

DEFAULT_NL_TO_MULTIPLE_SQL_JUDGE_PROMPT = (
    "<|sql judge prompt|>\n",
    """You are an expert data analyst adept at judging whether each SQL query in a list of SQL queries correctly answers a user's question.
A numbered list of SQL queries generated by an analyst to answer a question is shown below. The question and table information is also provided.
Respond with a list of each SQL number along with a 1 if the SQL query correctly answers the question, or a 0 if not.
To be considered correct, the query must return the data that the user asks for and that addresses the question, must apply the correct filters, consider one-to-many relationships correctly, etc.
Note that multiple queries could be correct, or all could be incorrect.

Table Information:

{table_info}

Generated SQL Queries:

{context_str}

Question: {question}

Now return a 1 or 0 for each SQL query based on whether it will yield a correct (1) or incorrect (0) result.""",
    "\n<|sql judge answer|>\n",
)

DEFAULT_INSTRUCT_PROMPT = ("<|prompt|>\n", "{question}", "\n<|answer|>\n")


DEFAULT_NL_TO_SQL_COT_PROMPT = (
    "<|cot sql prompt|>\n",
    """You are an expert data analyst adept at writing SQL queries to answer user questions.

You have access to the following relational tables, with schemas below.

Alongside each text column, in parentheses "()" you will see the top 3 values followed by "..." for columns with more than 5 distinct values, or the top 5 values otherwise. For timestamp and date columns you will see the min/max range of the column.

{table_info}

Write a SQL query to answer the following question, first outputting the chain-of-thought reasoning neccessary to go from question to answer, preceded by a "** Chain-of-Thought Reasoning **" header, and then the SQL query itself, preceded by a "** SQL Query **" header.
{input}""",
    "\n<|cot sql answer|>\n** Chain-of-Thought Reasoning **\n\n",
)

DEFAULT_NL_TO_SQL_COT_ERROR_PROMPT = (
    "<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n",
    DEFAULT_NL_TO_SQL_ERROR_PROMPT[1],
    "\n<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n",
)

CHART_GUIDELINES_AND_EXPECTED_OUTPUT = """Guidelines for Generating Vega-Lite Specification:
	•	Ensure the Vega-Lite JSON is fully valid and follows the latest Vega-Lite v5 schema.
	•	Select an appropriate visualization type (mark) based on the user’s intent.
	•	Encode X and Y axes based on the projected columns in the SQL query.
	•	Use color, size, shape, and tooltips if necessary to enhance the visualization.
	•	Assign appropriate data types:
	•	Use "type": "nominal" for categorical data (e.g., state, region).
	•	Use "type": "quantitative" for numerical values (e.g., sales, revenue).
	•	If a column is related to time, set "type": "temporal" and format it correctly.
	•	Ensure scaling, legends, and axis labels are correctly applied.
	•	Use meaningful tooltips to display additional information.
	•	The visualization should reference the data dynamically but should not include example data in the "values" section.

Expected Output:
	•	Return only a valid Vega-Lite JSON specification, without any extra explanation.
	•	Replace the "values" field with {data_placeholder} to indicate that real data will be injected dynamically.
"""

DEFAULT_NL_TO_VEGA_LITE_SPEC_PROMPT = (
    """<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are an expert in data visualization and the Vega-Lite specification language. Your task is to generate complete and valid **Vega-Lite JSON specifications** based on user requirements.

- Follow the **Vega-Lite schema** (https://vega.github.io/schema/vega-lite/v5.json).
- Ensure the output is correctly formatted as a **JSON specification** without any additional explanations.
- Use **inline data** for demonstration unless specified otherwise.
- Support **customization options**, including:
  - Different chart types (bar, line, scatter, etc.)
  - Custom X and Y axes
  - Color encoding based on a categorical field
  - Interactive features (filters, selections, tooltips, etc.)
- Always return a **fully structured Vega-Lite specification** without extra text.

Expected Output:
- Return only a valid Vega-Lite JSON specification without any extra explanation.
- Replace the `"values"` field with `{data_placeholder}` to indicate that real data will be injected dynamically.<|eot_id|>
<|start_header_id|>user<|end_header_id|>\n""",
    """You are an expert in data visualization and the Vega-Lite specification language. Your task is to generate a complete and valid **Vega-Lite JSON specification** based on the given user requirements.

### **Input Information:**
**Table Schemas:**
{table_schema}

**SQL Query:**
```sql
{sql_query}
```

### Sample Data (For Reference Only):
The following sample data represents the structure and expected values of the dataset:
{sample_data}

Generate an appropriate Vega Lite spec based on the below user's question.
"{question}"
""",
    """<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n""",
)
