from fastapi import UploadFile
from pydantic import BaseModel, Field


class BaseModelWithSessionID(BaseModel):
    """
    Pydantic Baseclass with session id field.
    """

    session_id: str = Field(
        ..., description="Search on the documents index where this heavydb sessionid is associated with."
    )


class AskDocumentRequest(BaseModelWithSessionID):
    """
    Ask question about the uploaded documents.
    """

    question: str = Field(..., description="Natural language question")
    filename: str | None = Field(
        default=None,
        description="Provide the filename if you want the question answered within the context of particular file",
    )

    class Config:
        json_schema_extra = {
            "examples": [{"session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "question": "What is NLP?"}]
        }


class AskDocumentResponse(BaseModel):
    """
    AskDocument endpoint's response model.
    """

    answer: str | None = Field(
        default=None, description="Answer returned by LLM by using the retrieved doc sources as context."
    )
    metadata: dict | None = Field(default=None, description="Metadata about the retrieved document sources")
    sources: list[str | tuple[str, dict]] = Field(
        default=[], description="Optional list of content sources used to derive the answer"
    )
    score: float | None = Field(default=None, description="Answer Evaluation Score")
    passing: bool | None = Field(default=None, description="Evaluation gets passed?")


class ListFilesRequest(BaseModelWithSessionID):
    """
    List all the uploaded documents specific to the database where the passsed session id belongs to.
    """

    class Config:
        json_schema_extra = {"examples": [{"session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}]}


class ListFilesResponse(BaseModel):
    """
    List of Documents.
    """

    documents: list[str] = Field(..., description="documents list")

    class Config:
        json_schema_extra = {"examples": [{"documents": ["foo.pdf", "bar.pdf"]}]}


class TableNamesRequest(BaseModelWithSessionID):
    """
    Table names request schema.
    """

    question: str = Field(..., description="Natural language question")

    class Config:
        json_schema_extra = {
            "examples": [{"session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "question": "What is NLP?"}]
        }


class AddORUpdateFactsRequest(BaseModelWithSessionID):
    """
    Add facts relevant to a particular database.
    """

    facts: str = Field(..., description="Facts")

    class Config:
        json_schema_extra = {"examples": [{"session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "facts": ""}]}


class GetFactsRequest(BaseModelWithSessionID):
    """
    Get facts relevant to a particular database.
    """

    class Config:
        json_schema_extra = {"examples": [{"session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}]}


class FactsResponse(BaseModel):
    """
    Facts response.
    """

    facts: str | None = Field(default=None, description="facts")

    class Config:
        json_schema_extra = {"examples": [{"facts": "asddsssddsdd"}]}


class AskFactsRequest(BaseModelWithSessionID):
    question: str = Field(..., description="Natural language question")
    only_retrieve: bool = Field(default=True, description="Retrieve Only")
    do_evaluate: bool = Field(default=False, description="Evaluate the response generated by llm")

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "question": "What is NLP?",
                    "only_retrieve": "true",
                    "do_evaluate": "false",
                }
            ]
        }


AskFactsResponse = AskDocumentResponse
