import asyncio
import json

from typing import TypedDict
from fastapi.concurrency import run_in_threadpool
from heavyiq.langchain import HeavyDB
from heavyiq.langchain.llms import LLMType, get_llm_by_type
from heavyiq.langchain.logging import log_chain_call_async
from collections.abc import AsyncIterable

from heavyiq.langchain.chains import (
    get_nl_to_sql_chain_by_llm,
)
from heavyiq.langchain.chains import NLtoAnswerChain
from heavyiq.api.models import QueryRequest, QueryResponse, QuestionRequest, QuestionResponse
from heavyiq.config import get_config
from heavyiq.logging_utils import get_heavyiq_logger
from heavyiq.api.utils import wrap_done
from heavyiq.langchain.callbacks.stream_callback import StreamingChainCallbackHandler, StreamEvent as Event


class MessageDict(TypedDict):
    type: str
    text: str


class EventMessage:
    def __init__(self, event: Event, message: str) -> None:
        self.event = event
        self.message = message

    @classmethod  # type: ignore
    def from_dict(cls: type["EventMessage"], message_dict: MessageDict) -> "EventMessage":
        message_type = message_dict["type"]
        if message_type == "step":
            event = Event.step
        elif message_type == "next_token":
            event = Event.next_token
        elif message_type == "output":
            event = Event.output
        elif message_type == "error":
            event = Event.error
        else:
            raise ValueError(f"Invalid message type {message_type}")
        return cls(event=event, message=message_dict["text"])

    def __str__(self) -> str:
        return f"event: {self.event.name}\ndata: {self.message}\n\n"


async def streaming_query(request: QueryRequest, db: HeavyDB, stream_llm_tokens: bool = False) -> AsyncIterable[str]:
    """
    Asynchronously streams a query based on the provided message.

    Args:
        request (QueryRequest): request payload
        db (HeavyDB): a HeavyDB instance.
        stream_tokens (bool): stream also the tokens generated by the llm else it streams the steps alone.

    Returns:
        An asynchronous iterable that streams the query results as strings.

    Yields:
        AsyncIterable[str]: A stream of strings representing the query results.
    """

    callback, config, logger = StreamingChainCallbackHandler(), get_config(), get_heavyiq_logger()

    yield str(EventMessage(Event.step, "Finding the suitable LLM..."))
    llm = await run_in_threadpool(
        get_llm_by_type, LLMType.NL_TO_SQL, temperature=0.0, streaming=stream_llm_tokens, callbacks=[callback]
    )
    yield str(EventMessage(Event.step, f"Found {llm.__class__.__name__} LLM for processing."))
    chain_cls = get_nl_to_sql_chain_by_llm(llm=llm)
    file_callback_handler = logger.async_langchain_cb_handler(to_stdout=config.log_to_stdout)
    chain = chain_cls(llm=llm, database=db, callbacks=[file_callback_handler, callback], tags=["rest-api", "query-stream-endpoint"])  # type: ignore
    chain_input = {chain.input_key: request.question, "tables": request.tables}

    # Begin a task that runs in the background.
    task = asyncio.create_task(
        wrap_done(log_chain_call_async(chain, chain_input, ""), callback.done),
    )

    async for token in callback.aiter():
        yield str(EventMessage.from_dict(token))  # type: ignore

    res = await task
    feedback_id = str(res["__run"].run_id) if "__run" in res else ""
    response_dict = QueryResponse(
        sql=res[chain.output_key],
        sql_complexity=res[chain.output_complexity_key],
        feedback_id=feedback_id,
        logprobs=res[chain.output_logprobs_key],
    ).dict()
    yield str(EventMessage(Event.output, json.dumps(response_dict)))


async def streaming_question(request: QuestionRequest, db: HeavyDB, stream_llm_tokens: bool = False):
    """
    Asynchronously streams steps and tokens involved in generating an answer based on the provided message.

    Args:
        request (QuestionRequest): request payload
        db (HeavyDB): a HeavyDB instance.
        stream_tokens (bool): stream also the tokens generated by the llm else it streams the steps alone.

    Returns:
        An asynchronous iterable that streams the question results as strings.

    Yields:
        AsyncIterable[str]: A stream of strings representing the steps or tokens.
    """
    callback, config, logger = StreamingChainCallbackHandler(), get_config(), get_heavyiq_logger()
    file_callback_handler = logger.async_langchain_cb_handler(to_stdout=config.log_to_stdout)

    yield str(EventMessage(Event.step, "Finding the suitable LLM..."))
    nl_sql_llm = await run_in_threadpool(
        get_llm_by_type, LLMType.NL_TO_SQL, temperature=0.0, streaming=stream_llm_tokens, callbacks=[callback]
    )
    yield str(EventMessage(Event.step, f"Found {nl_sql_llm.__class__.__name__} LLM for processing."))

    nl_sql_chain = get_nl_to_sql_chain_by_llm(llm=nl_sql_llm)(
        llm=nl_sql_llm,
        database=db,
        callbacks=[file_callback_handler, callback],
        tags=["rest-api", "question-stream-endpoint"],
    )
    llm = await run_in_threadpool(
        get_llm_by_type, LLMType.SQL_TO_ANSWER, temperature=0.0, streaming=stream_llm_tokens, callbacks=[callback]
    )
    chain = NLtoAnswerChain(
        llm=llm,
        nl_sql_chain=nl_sql_chain,
        database=db,
        callbacks=[file_callback_handler, callback],
        tags=["rest-api", "question-endpoint"],
    )
    chain_input = {chain.input_key: request.question, "tables": request.tables}

    # Begin a task that runs in the background.
    task = asyncio.create_task(
        wrap_done(log_chain_call_async(chain, chain_input, ""), callback.done),
    )

    async for token in callback.aiter():
        yield str(EventMessage.from_dict(token))  # type: ignore

    res = await task
    feedback_id = str(res["__run"].run_id) if "__run" in res else ""
    response_dict = QuestionResponse(
        answer=res[chain.output_key] or res[chain.output_fail_reason_key],
        sql=res[chain.output_sql_key],
        sql_result=res[chain.output_results_key],
        sql_complexity=res[chain.output_sql_complexity_key],
        feedback_id=feedback_id,
    ).dict()
    yield str(EventMessage(Event.output, json.dumps(response_dict)))
