from collections.abc import AsyncGenerator

from heavyiq.api.models import QueryRequest
from heavyiq.langchain import HeavyDB
from heavyiq.langchain.heavydb import heavydb_context
from heavyiq.lcel.chains import sql_chain
from heavyiq.lcel.runnables import StreamStepsRunnableWrapper
from heavyiq.lcel.types import StepDict


async def streaming_query(
    request: QueryRequest, db: HeavyDB, stream_llm_tokens: bool = False
) -> AsyncGenerator[StepDict, None]:
    """
    Asynchronously streams a query based on the provided message.
    Args:
        request (QueryRequest): request payload
        db (HeavyDB): a HeavyDB instance.
        stream_tokens (bool): stream also the tokens generated by the llm else it streams the steps alone.
    Returns:
        An asynchronous iterable that streams the query results as StepDict.
    Yields:
        AsyncIterable[StepDict]: A stream of StepDict representing the query results.
    """
    async with heavydb_context(db):
        stream_chain = StreamStepsRunnableWrapper(sql_chain)
        async for step in stream_chain.start(request.dict()):
            yield step
