from collections.abc import AsyncIterator

from heavyiq.api.models import QueryRequest, QuestionRequest
from heavyiq.langchain import HeavyDB
from heavyiq.langchain.heavydb import heavydb_context
from heavyiq.lcel.callbacks.file_callback import LogFileCallbackHandler
from heavyiq.lcel.chains import answer_chain, sql_chain, sql_cot_chain
from heavyiq.lcel.runnables import StreamLLMRunnableWrapper, StreamStepsRunnableWrapper
from heavyiq.lcel.types import StepDict


async def streaming_query(request: QueryRequest, db: HeavyDB) -> AsyncIterator[StepDict]:
    """
    Asynchronously streams a query based on the provided message.
    Args:
        request (QueryRequest): request payload
        db (HeavyDB): a HeavyDB instance.
        stream_tokens (bool): stream also the tokens generated by the llm else it streams the steps alone.
    Returns:
        An asynchronous iterable that streams the query results as StepDict.
    Yields:
        AsyncIterable[StepDict]: A stream of StepDict representing the query results.
    """
    async with heavydb_context(db):
        stream_chain = StreamStepsRunnableWrapper(sql_chain)
        async for step in stream_chain.start(request.dict(), config={"callbacks": [LogFileCallbackHandler()]}):
            yield step


async def streaming_query_with_cot(request, db) -> AsyncIterator[StepDict]:
    async with heavydb_context(db):
        stream_chain = StreamLLMRunnableWrapper(sql_cot_chain)
        async for step in stream_chain.start(request.dict(), config={"callbacks": [LogFileCallbackHandler()]}):
            yield step


async def streaming_question(request: QuestionRequest, db: HeavyDB) -> AsyncIterator[StepDict]:
    """
    Asynchronously streams a question(ie. nl to answer chain) based on the provided message.
    """
    async with heavydb_context(db):
        stream_chain = StreamStepsRunnableWrapper(answer_chain)
        async for step in stream_chain.start(request.dict(), config={"callbacks": [LogFileCallbackHandler()]}):
            yield step
